# -*- coding: utf-8 -*-
"""doctr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDglZ8lGizDhR4CY5zo2dSIE0v49_yGJ
"""

!pip install python-doctr[torch] pdf2image PyMuPDF -q

from doctr.io import DocumentFile
from doctr.models import ocr_predictor
from pdf2image import convert_from_path
import fitz  # PyMuPDF
import os

# Colab'e PDF yüklemek için arayüz
from google.colab import files
uploaded = files.upload()

pdf_path = list(uploaded.keys())[0]
print(f"Yüklenen dosya: {pdf_path}")

# DocTR modelini başlat
model = ocr_predictor(pretrained=True)

# PDF dosyasını yükle
doc = DocumentFile.from_pdf(pdf_path)

# OCR işlemini çalıştır
result = model(doc)

# OCR sonucunu text formatında al
text_output = result.render()  # sadece metin, koordinatsız

# İlk 500 karakteri görelim
print(text_output[:500])

md_path = os.path.splitext(pdf_path)[0] + ".md"
txt_path = os.path.splitext(pdf_path)[0] + ".txt"

with open(md_path, "w", encoding="utf-8") as md_file:
    md_file.write("# OCR Çıktısı\n\n")
    md_file.write(text_output)

with open(txt_path, "w", encoding="utf-8") as txt_file:
    txt_file.write(text_output)

print(f"Kaydedildi:\n- {md_path}\n- {txt_path}")