# -*- coding: utf-8 -*-
"""tesseract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10eEXwqj4gf2Outzj8WcMqgN5-kBcoIS-
"""

# 🔧 1. Gerekli kütüphaneleri yükle
!apt install tesseract-ocr -y
!apt install tesseract-ocr-tur -y  # Türkçe dil paketi
!pip install pytesseract Pillow PyMuPDF

import fitz  # PyMuPDF
import pytesseract
from PIL import Image
import io

pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'
lang = "tur"  # Türkçe OCR

# 🔹 Yüklediğin dosyanın adı burada
pdf_path = "/content/disiplin_amirleri_yonetmeligi.pdf"   # dosya adını buraya yaz

doc = fitz.open(pdf_path)
all_text = ""

for i, page in enumerate(doc):
    print(f"📄 Sayfa {i+1} işleniyor...")
    pix = page.get_pixmap(dpi=300)
    img = Image.open(io.BytesIO(pix.tobytes("png")))
    text = pytesseract.image_to_string(img, lang=lang)
    all_text += f"\n\n=== SAYFA {i+1} ===\n{text}"

with open("pdf_metni.txt", "w", encoding="utf-8") as f:
    f.write(all_text)

print("\n✅ OCR tamamlandı! Metin 'pdf_metni.txt' dosyasına kaydedildi.")

import fitz  # PyMuPDF
import pytesseract
from PIL import Image
import io

pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'
lang = "tur"  # Türkçe OCR

# 🔹 Yüklediğin dosyanın adı burada
pdf_path = "/content/2021_kurban.pdf"   # dosya adını buraya yaz

doc = fitz.open(pdf_path)
all_text = ""

for i, page in enumerate(doc):
    print(f"📄 Sayfa {i+1} işleniyor...")
    pix = page.get_pixmap(dpi=300)
    img = Image.open(io.BytesIO(pix.tobytes("png")))
    text = pytesseract.image_to_string(img, lang=lang)
    all_text += f"\n\n=== SAYFA {i+1} ===\n{text}"

with open("pdf_metni.txt", "w", encoding="utf-8") as f:
    f.write(all_text)

print("\n✅ OCR tamamlandı! Metin 'pdf_metni.txt' dosyasına kaydedildi.")

pip install python-doctr[torch] pymupdf

from doctr.io import DocumentFile
from doctr.models import ocr_predictor
import fitz  # PyMuPDF
import json

# 📄 1. PDF yolu
pdf_path = "/content/disiplin_amirleri_yonetmeligi.pdf"

# 🔹 2. docTR OCR modelini yükle
model = ocr_predictor(pretrained=True)

# 🔹 3. PDF'i oku (taranmış olduğu için her sayfa görsel olarak alınır)
pdf_doc = fitz.open(pdf_path)
images = []

for page in pdf_doc:
    pix = page.get_pixmap(dpi=300)
    img_bytes = pix.tobytes("png")
    images.append(img_bytes)

# 🔹 4. docTR modeline OCR gönder
doc = DocumentFile.from_images(images)
result = model(doc)

# 🔹 5. Sonucu JSON olarak al
output = result.export()

# 🔹 6. Metin + tablo yapısını ayır
plain_text = ""
tables = []

for page_idx, page in enumerate(output["pages"]):
    plain_text += f"\n\n=== SAYFA {page_idx + 1} ===\n"
    for block in page["blocks"]:
        block_type = block["type"]
        content = " ".join([w["value"] for l in block["lines"] for w in l["words"]])
        if "table" in block_type.lower():
            tables.append(content)
        else:
            plain_text += content + "\n"

# 🔹 7. Düz metni kaydet
with open("tum_metn.txt", "w", encoding="utf-8") as f:
    f.write(plain_text)

# 🔹 8. Tablo metinlerini kaydet (dilersen CSV’ye dönüştür)
with open("tablolar.txt", "w", encoding="utf-8") as f:
    for t in tables:
        f.write(t + "\n\n")

# (İsteğe bağlı) JSON çıktısı
with open("ocr_sonuc.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print("✅ Tüm sayfalar işlendi! Metin ve tablolar ayrı kaydedildi.")